id: I85125EC4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T13:39:29+00:00'
last_modified: '2022-06-07T13:55:12.300815+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74357
  title: ལྕང་སྐྱ་རོལ་པའི་རྡོ་རྗེའི་རྣམ་ཐར་སྙན་ངག་ཚིགས་བཅད་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    99F9:
      image_group_id: I4CZ74359
      title: ''
      total_pages: 169
      order: 1
      base_file: 99F9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
