id: I85125EC4
legacy_id: P001651
ocr_import_info:
  bdrc_scan_id: W4CZ74357
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T13:39:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:03:52.488229+00:00'
last_modified: 2022-09-04 05:04:00.656824
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ74357
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ74357
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྕང་སྐྱ་རོལ་པའི་རྡོ་རྗེའི་རྣམ་ཐར་སྙན་ངག་ཚིགས་བཅད་ཕྱོགས་བསྒྲིགས།
  author: ཐུའུ་བཀྭན ༠༣་བློ་བཟང་ཆོས་ཀྱི་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.635885435052413
  ocr_word_median_confidence_index: 0.6800000071525574
quality: null
bases:
  I4CZ74359:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74359
      total_pages: 169
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ74359.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.635885435052413
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
