id: P001651
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74357
  title: ལྕང་སྐྱ་རོལ་པའི་རྡོ་རྗེའི་རྣམ་ཐར་སྙན་ངག་ཚིགས་བཅད་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    99f1f9caab2042b09c808c982eed2cec:
      image_group_id: I4CZ74359
      title: ''
      volume_number: 1
      total_pages: 169
